version: "3.9"
services:
  gateway:
    working_dir: /app
    build: ./services/gateway
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT:-8080}
      - AUTH_URL=http://auth:3001
      - CATALOG_URL=http://catalog:3002
      - ORDERS_URL=http://orders:3003
      - PAYMENTS_URL=http://payments:3004
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    depends_on: [auth, catalog, orders, payments]
  auth:
    working_dir: /app
    build: ./services/auth
    environment:
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - AUTH_PORT=${AUTH_PORT:-3001}
    volumes:
      - auth_data:/app/prisma
  catalog:
    working_dir: /app
    build: ./services/catalog
    environment:
      - CATALOG_PORT=${CATALOG_PORT:-3002}
    volumes:
      - catalog_data:/app/prisma
  orders:
    working_dir: /app
    build: ./services/orders
    environment:
      - ORDERS_PORT=${ORDERS_PORT:-3003}
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - CATALOG_URL=http://catalog:3002
      - PAYMENTS_URL=http://payments:3004
    volumes:
      - orders_data:/app/prisma
  payments:
    working_dir: /app
    build: ./services/payments
    environment:
      - PAYMENTS_PORT=${PAYMENTS_PORT:-3004}
volumes:
  auth_data:
  catalog_data:
  orders_data:
